version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
            - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8000:80"
        depends_on:
            - mysql
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        command: apache2-foreground
        networks:
            laravel_net:
                ipv4_address: 172.28.0.2

    mysql:
        image: mysql:8
        container_name: mysql_user_auth
        ports:
            - "3308:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "cCvD3E#6$&16"
            MYSQL_DATABASE: user_auth
        restart: unless-stopped
        networks:
            laravel_net:
                ipv4_address: 172.28.0.3

    composer:
        image: composer:2
        container_name: composer
        volumes:
            - ./:/app
        working_dir: /app
        tty: true
        stdin_open: true
        entrypoint: ["sh"]
        networks:
            laravel_net:
                ipv4_address: 172.28.0.4

    vite:
        image: node:18
        container_name: vite
        working_dir: /app
        volumes:
            - ./:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        networks:
            laravel_net:
                ipv4_address: 172.28.0.5

volumes:
    mysql_data:

networks:
    laravel_net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/16
